# Generated by Django 4.2.4 on 2024-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/images')),
                ('description', models.TextField()),
            ],
        ),
    ]
