# Generated by Django 4.2.4 on 2024-05-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
