# Generated by Django 4.2.4 on 2024-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='files/images'),
        ),
    ]
