# Generated by Django 4.2.4 on 2024-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0005_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVINGROOM', 'Living room'), ('BATHROOM', 'Bath room')], default='KITCHEN'),
        ),
    ]
