# Generated by Django 4.2.4 on 2024-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVINGROOM', 'Living room'), ('BATHROOM', 'Bath room'), ('BEDROOM', 'Bed room')], default='KITCHEN'),
        ),
    ]
