# Generated by Django 4.2.4 on 2024-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0011_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVINGROOM', 'Living room'), ('BATHROOM', 'Bath room'), ('BEDROOM', 'Bed room'), ('EXTERIOR', 'Exterior')], default='KITCHEN'),
        ),
    ]
