# Generated by Django 4.2.4 on 2024-08-05 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0014_rename_created_date_item_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVINGROOM', 'Living room'), ('DOOR', 'door'), ('BATHROOM', 'Bath room'), ('BEDROOM', 'Bed room'), ('EXTERIOR', 'Exterior'), ('OTHER', 'Other')], default='KITCHEN')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('LIVINGROOM', 'Living room'), ('DOOR', 'door'), ('BATHROOM', 'Bath room'), ('BEDROOM', 'Bed room'), ('EXTERIOR', 'Exterior'), ('OTHER', 'Other')], default='KITCHEN'),
        ),
    ]
