# Generated by Django 4.2.4 on 2024-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0015_image_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
