# Generated by Django 4.2.4 on 2024-08-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghadboungroup', '0016_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
